### ISSUE TITLE
Icons not functioning

### ISSUE THREAD

**Issue by heatherlyall** [heatherlyall/header-icons#1]
Hey, my icons are huge and they are all pushed to one side. I put the correct width and I keep trying to get them to align on either side, but they still look huge and neither of them will budge @thomasjbradley

**Comment by thomasjbradley** [comment]
The `<h2>` should be inside the same `<div>` as the images & that div should be a Flexbox.

**Comment by heatherlyall** [comment]
I've tried that and the title got moved to the left side and the pictures are still the same size as before @thomasjbradley

**Comment by thomasjbradley** [comment]
The order of your HTML matters to Flexbox.
